baseurl: /PyStretch
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/jlaura/PyStretch
